---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-server
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: cert-manager-issuer
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/media-server
  prune: true
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tools
  namespace: flux-system
spec:
  dependsOn:
    - name: longhorn
    - name: cert-manager-issuer
  interval: 1h
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/tools
  prune: true
  wait: true
---
