---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: radarr
spec:
  selector:
    app.kubernetes.io/name: radarr
  type: ClusterIP
  ports:
    - name:  http
      port:  7878
      protocol: TCP
---
