---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: sonarr
spec:
  selector:
    app.kubernetes.io/name: sonarr
  type: ClusterIP
  ports:
    - name:  http
      port:  8989
      protocol: TCP
---
