---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-sonarr-pvc
  namespace: media-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
---
