apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: acme-issuer
spec:
  acme:
    email: tomislav@nikic.org

    # Letsencrypt Production
    server: https://acme-v02.api.letsencrypt.org/directory

    privateKeySecretRef:
      name: issuer-account-key

    solvers:
    # DNS Challenge:
    - dns01:
        cloudflare:
          email: tomislav@nikic.org
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
