---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  selector:
    app.kubernetes.io/name: prowlarr
  type: ClusterIP
  ports:
    - name:  http
      port:  9696
      protocol: TCP
---
