apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
  namespace: media-server
  labels:
    app.kubernetes.io/name: prowlarr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: prowlarr
  template:
    metadata:
        labels:
          app.kubernetes.io/name: prowlarr
    spec:
      containers:
        - image: lscr.io/linuxserver/prowlarr:1.12.2
          name: prowlarr
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: http
              containerPort: 9696
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-prowlarr-pvc
