apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: media-server
  namespace: media-server
spec:
  secretName: media-server
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.home.nikic.org"
