apiVersion: apps/v1
kind: Deployment
metadata:
  name: calibre
  namespace: books
  labels:
    app.kubernetes.io/name: calibre
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: calibre
  template:
    metadata:
        labels:
          app.kubernetes.io/name: calibre
    spec:
      containers:
        - image: lscr.io/linuxserver/calibre:7.6.0
          name: calibre
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: calibre
              containerPort: 8080
              protocol: TCP
            - name: calibre-server
              containerPort: 8081
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /config
              name: config
        - image: lscr.io/linuxserver/calibre-web:0.6.21
          name: calibre-web
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: calibre-web
              containerPort: 8083
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /config
              name: config-web
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: 10.0.3.3
            path: /mnt/storage/media
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-calibre-pvc
        - name: config-web
          persistentVolumeClaim:
            claimName: longhorn-calibre-web-pvc
