---
apiVersion: v1
kind: Service
metadata:
  name: calibre
  namespace: books
  labels:
    app.kubernetes.io/name: calibre
spec:
  selector:
    app.kubernetes.io/name: calibre
  type: LoadBalancer
  loadBalancerIP: 10.0.3.101
  ports:
    - name:  calibre
      port:  8080
      protocol: TCP
    - name:  calibre-server
      port:  8081
      protocol: TCP
    - name:  calibre-web
      port:  8083
      protocol: TCP
---
