---
apiVersion: v1
kind: Service
metadata:
  name: komf
  namespace: books
  labels:
    app.kubernetes.io/name: komf
spec:
  selector:
    app.kubernetes.io/name: komf
  type: ClusterIP
  ports:
    - name:  http
      port:  8085
      protocol: TCP
---
