apiVersion: apps/v1
kind: Deployment
metadata:
  name: komf
  namespace: books
  labels:
    app.kubernetes.io/name: komf
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: komf
  template:
    metadata:
        labels:
          app.kubernetes.io/name: komf
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      initContainers:
        - name: create-application-yml
          image: alpine
          command: ["/bin/sh","-c"] 
          args:
          - >-
            cat > /config/application.yml <<EOF
              komga:
                baseUri: "https://read.home.nikic.org"
                komgaUser: "tomislav@nikic.org"
                komgaPassword: "admin"
                eventListener:
                  enabled: true
                  libraries: [ ]
                metadataUpdate:
                  default:
                    libraryType: "MANGA"
                    updateModes: [ API, COMIC_INFO ]
                    aggregate: false
                    mergeTags: false
                    mergeGenres: false
                    bookCovers: true
                    seriesCovers: true
                    overrideExistingCovers: true
                    postProcessing:
                      seriesTitle: true
                      seriesTitleLanguage: "en"
                      alternativeSeriesTitles: true
                      alternativeSeriesTitleLanguages:
                        - "ja"
                        - "ko"
                      orderBooks: true
              metadataProviders:
                defaultProviders:
                  mangaUpdates:
                    priority: 30
                    enabled: true
                    mediaType: "MANGA"
                    authorRoles: [ "WRITER" ]
                    artistRoles: [ "PENCILLER","INKER","COLORIST","LETTERER","COVER" ]
                  aniList:
                    priority: 10
                    enabled: true
                    mediaType: "MANGA"
                    tagsScoreThreshold: 60
                    tagsSizeLimit: 15
                  mangaDex:
                    priority: 20
                    enabled: true
            EOF
          volumeMounts:
            - mountPath: /config
              name: config
      containers:
        - image: sndxr/komf:0.33.0
          name: komf
          env:
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: http
              containerPort: 8085
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: 10.0.3.3
            path: /mnt/storage/media
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-komf-pvc
