apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant
  namespace: tools
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: home-assistant
  template:
    metadata:
        labels:
          app.kubernetes.io/name: home-assistant
    spec:
      containers:
        - image: ghcr.io/home-assistant/home-assistant:2024.2.2
          name: home-assistant
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config

          # Probes
          livenessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 8123
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5

      restartPolicy: Always
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-home-assistant-pvc
