---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: tools
  labels:
    app.kubernetes.io/name: home-assistant
spec:
  selector:
    app.kubernetes.io/name: home-assistant
  type: ClusterIP
  ports:
    - name:  http
      port:  8123
      protocol: TCP
---
