apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-home-assistant-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
