---
apiVersion: v1
kind: Service
metadata:
  name: sabnzb
  namespace: media-server
  labels:
    app.kubernetes.io/name: sabnzb
spec:
  selector:
    app.kubernetes.io/name: sabnzb
  type: ClusterIP
  ports:
    - name:  http
      port:  8080
      protocol: TCP
---
