apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzb
  namespace: media-server
  labels:
    app.kubernetes.io/name: sabnzb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: sabnzb
  template:
    metadata:
        labels:
          app.kubernetes.io/name: sabnzb
    spec:
      containers:
        - image: lscr.io/linuxserver/sabnzbd:4.2.2
          name: sabnzb
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: 10.0.3.3
            path: /mnt/storage/media
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-sabnzb-pvc
