apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: books
  namespace: books
spec:
  secretName: books
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.home.nikic.org"
