apiVersion: apps/v1
kind: Deployment
metadata:
  name: fmd
  namespace: books
  labels:
    app.kubernetes.io/name: fmd
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels: 
      app.kubernetes.io/name: fmd
  template:
    metadata:
        labels:
          app.kubernetes.io/name: fmd
    spec:
      containers:
        - image: banhcanh/docker-fmd2:kasm-v3
          name: fmd
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: Europe/Vienna
            - name: THRESHOLD_MINUTES
              value: "5" 
            - name: TRANSFER_FILE_TYPE
              value: ".cbz"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /app/FMD2/userdata
              name: config
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: 10.0.3.3
            path: /mnt/storage/media
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-fmd-pvc
