apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-fmd-pvc
  namespace: books
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
