---
apiVersion: v1
kind: Service
metadata:
  name: fmd
  namespace: books
  labels:
    app.kubernetes.io/name: fmd
spec:
  selector:
    app.kubernetes.io/name: fmd
  type: ClusterIP
  ports:
    - name:  http
      port:  3000
      protocol: TCP
---
