apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-vaultwarden-pvc
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Mi
