apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tools
  namespace: tools
spec:
  secretName: tools
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer
  dnsNames:
    - "*.home.nikic.org"
