---
apiVersion: v1
kind: Service
metadata:
  name: komga
  namespace: books
  labels:
    app.kubernetes.io/name: komga
spec:
  selector:
    app.kubernetes.io/name: komga
  type: ClusterIP
  ports:
    - name:  http
      port:  25600
      protocol: TCP
---
