---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komga
  namespace: books
  labels:
    app.kubernetes.io/name: komga
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: komga
  template:
    metadata:
        labels:
          app.kubernetes.io/name: komga
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - image: gotson/komga
          name: komga
          env:
            - name: TZ
              value: Europe/Vienna
          ports:
            - name: http
              containerPort: 25600
              protocol: TCP
          volumeMounts:
            - mountPath: /storage/media
              name: media
            - mountPath: /config
              name: config
      restartPolicy: Always
      volumes:
        - name: media
          nfs:
            server: 10.0.3.3
            path: /mnt/storage/media
        - name: config
          persistentVolumeClaim:
            claimName: longhorn-komga-pvc
---
